---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul
  namespace: consul

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: consul
  name: consul
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul
  namespace: consul
roleRef:
  kind: Role
  name: consul
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: consul
